- app/controller/api/data.js
- app/middleware/context_cors.js
- app/middleware/context_delay.js
- app/middleware/error_handler.js
- app/router.js
- package.json
- move cors function into middleware
- fix json response issue
> feat: add delay function

- app/controller/api/data.js
- allow set proxy server cookie for session
> feat: support proxy headers

- Dockerfile
> fixed docker node version

- Dockerfile
- healthcheck.js
- package.json
Added support docker health check
> Added support docker healthcheck

- package.json
- test/app/controller/project.test.js
> added controller project test

- test/app/service/project.test.js
> Added project service test

- config/config.unittest.js
- test/app/controller/data.test.js
added controller data test for index method
> added constroller test for index method

- app/controller/api/data.js
- test/app/controller/data.test.js
> fixed response body when status code is not 200

- .dockerignore
- Dockerfile
- agent.js
- app.js
- app/controller/page.js
- app/middleware/socket_emit.js
- app/socket.js
- config/config.default.js
- entrypoint.sh
- index.js
- lib/update.js
- package.json
- update Dockerfile
- add npm start script for docker
> feat: npm start

- app/controller/api/sdk.js
- app/service/database.js
> fix: async syntax

- app/router.js
- config/config.default.js
> feat: support cors for api

- lib/update.js
- hide logo if process.env.CI is present.
> feat: not show logo in ci runner

- docs/guide/webpack-tutorial.md
- docs/zh/guide/webpack-tutorial.md
update for https://github.com/macacajs/datahub-proxy-middleware/pull/10
> docs(webpack): fix regex

- lib/update.js
- update host, avoid `Network Error`
> feat: update registry host

- .husky/commit-msg
- .husky/pre-commit
- app/controller/data.js
- app/controller/page.js
- config/config.default.js
- index.js
- macaca-datahub.config.js
- package.json
- view/src/components/Experiment.jsx
- view/src/components/InterfaceDetail/InterfaceProxyConfig.jsx
- view/src/components/forms/SceneForm.jsx
- add server feature config
- enable javascript mode by default
- add `process.env.ENABLE_JAVASCRIPT` to start config
- add `process.env.ENABLE_REQUEST_PROXY` to start config
- usage
```javascript
module.exports = {
port: 7001,
enableJavascript: false,
enableRequestProxy: false,
};
```
> feat: add server feature config

- .dockerignore
- Dockerfile
- package.json
> feat: update Dockerfile

- database/migrations/20220106062223-rebuild-unique-indexes.js
> fix: clean dirty data & rebuild unique indexes

- package.json
> fix: server startup failure

- config/config.default.js
- package.json
- view/src/components/InterfaceDetail/InterfaceSceneList.jsx
- view/src/components/InterfaceDetail/index.js
- view/src/components/InterfaceList.less
- view/src/components/InterfaceList.module.less
- view/src/components/forms/SceneForm.jsx
- view/src/pages/Project.jsx
> fix: scene update and change bug

- app/model/Group.js
- app/model/Interface.js
- app/service/database.js
- app/service/group.js
- app/service/interface.js
- app/service/project.js
- app/service/transfer.js
- config/locale/en-US.js
- config/locale/zh-CN.js
- database/migrations/20221116173411-add-indexes-for-group.js
- database/migrations/20221116173411-update-indexes.js
- test/controller/api/group.test.js
- test/fixtures/unittest_new_data/one.json
- test/fixtures/unittest_new_data/one/api#v2.group.json
- test/fixtures/unittest_new_data/one/api#v2.group/GET_one.json
- test/fixtures/unittest_new_data/one/api#v2.group/GET_one/scene/default.json
- test/fixtures/unittest_new_data/one/api#v2.group/GET_one/schema/request.json
- test/service/database.test.js
- test/service/group.test.js
- test/service/project.test.js
- view/src/components/InterfaceList.jsx
- view/src/components/forms/GroupForm.jsx
- view/src/locale/en_US.js
- view/src/locale/zh_CN.js
> fix: data sync bug
